# Generated by Django 6.0 on 2025-12-17 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название задачи')),
                ('source', models.CharField(choices=[('hh', 'HeadHunter'), ('habr', 'Habr Career')], default='hh', max_length=50, verbose_name='Источник')),
                ('search_query', models.CharField(default='python', max_length=255, verbose_name='Поисковый запрос')),
                ('area', models.CharField(default='1', max_length=100, verbose_name='Регион')),
                ('per_page', models.IntegerField(default=50, verbose_name='Кол-во вакансий на странице')),
                ('pages', models.IntegerField(default=1, verbose_name='Кол-во страниц')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Последний запуск')),
            ],
            options={
                'verbose_name': 'Задача парсинга',
                'verbose_name_plural': 'Задачи парсинга',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=50, unique=True, verbose_name='ID вакансии')),
                ('name', models.CharField(max_length=500, verbose_name='Название вакансии')),
                ('company', models.CharField(max_length=500, verbose_name='Компания')),
                ('salary_from', models.IntegerField(blank=True, null=True, verbose_name='Зарплата от')),
                ('salary_to', models.IntegerField(blank=True, null=True, verbose_name='Зарплата до')),
                ('salary_currency', models.CharField(blank=True, choices=[('RUR', 'Рубли'), ('USD', 'Доллары'), ('EUR', 'Евро')], max_length=10, null=True, verbose_name='Валюта')),
                ('salary_gross', models.BooleanField(null=True, verbose_name='Зарплата до вычета налогов')),
                ('experience', models.CharField(blank=True, max_length=100, null=True, verbose_name='Опыт работы')),
                ('schedule', models.CharField(blank=True, max_length=100, null=True, verbose_name='График работы')),
                ('employment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип занятости')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание вакансии')),
                ('skills', models.JSONField(default=list, verbose_name='Навыки')),
                ('area', models.CharField(max_length=200, verbose_name='Регион')),
                ('url', models.URLField(max_length=500, verbose_name='Ссылка на вакансию')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('parse_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='parser_app.parsetask', verbose_name='Задача парсинга')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-published_at'],
            },
        ),
    ]
